### ISSUE TITLE
Integration avec HACS KO

### ISSUE THREAD

**Issue by arnaud-42** [francispoisson/hilo#1]
Je viens d'essayer d'installer cette integration via HACS mais quand j'ajoute ce repo j'ai le message suivant : Repostitory structure for 0.2 is not compliant

**Comment by isbkch** [comment]
C'est vrai qu'une integration HACS rendra les choses bien plus facile

**Comment by francispoisson** [comment]
J'ai essayé de modifier la structure pour que ça fonctionne, mais je n'ai pas HACS pour tester.

**Comment by francispoisson** [comment]
Ça s'en vient:
![image](https://user-images.githubusercontent.com/10672200/106546753-e48c1a80-64d9-11eb-8543-95da897ec6d1.png)

![image](https://user-images.githubusercontent.com/10672200/106546772-ed7cec00-64d9-11eb-8234-62434ccf133a.png)

**Comment by isbkch** [comment]
Cool! Quand j'essaie de l'ajouter comme custom repository, j'ai toujours le message comme quoi ce n'est pas compliant

**Comment by francispoisson** [comment]
Ça fonctionne maintenant.

**Comment by francispoisson** [comment]
![image](https://user-images.githubusercontent.com/10672200/106619195-51d19700-653e-11eb-830a-bd4a9207772f.png)

**Comment by arnaud-42** [comment]
Je confirme ca fonctionne merci
