### ISSUE TITLE
Pas de donnés depuis la dernière mise à jour

### ISSUE THREAD

**Issue by isbkch** [francispoisson/hilo#11]
Les cercles des thermostats n'affichent plus la température actuelle et la température réglé depuis que j'ai mis à jour le module depuis HACS et redémarrer il y'a quelques minutes  

![C507FF54-4457-4215-BCBB-6D209C85AD56](https://user-images.githubusercontent.com/216867/107098135-8a8e9c00-67dc-11eb-94da-8089dc41dbda.jpeg)

**Comment by isbkch** [comment]
C'est toujours le cas...

**Comment by francispoisson** [comment]
C'est pourtant la même version qu'il y a trois jours. Des erreurs dans le log?

**Comment by isbkch** [comment]
Non je vois rien dans les logs. ça a arreté de fonctionner apres que j'ai installé la mise a jour du 2021.2.1 ([celle du 5 fevrier](https://www.home-assistant.io/blog/2021/02/03/release-20212/))

<img width="1307" alt="Screen Shot 2021-02-06 at 6 01 29 PM" src="https://user-images.githubusercontent.com/216867/107131547-795d9200-68a5-11eb-9513-130fdf817152.png">

**Comment by skimaniac** [comment]
j'avais le même problème et c'est en cliquant sur les boutons que finalement c'est revenu.
[
<img width="166" alt="Capture d’écran, le 2021-02-06 à 18 16 53" src="https://user-images.githubusercontent.com/44727542/107131798-c2aee100-68a7-11eb-9c71-7a69fd993fa6.png">
](url)

**Comment by isbkch** [comment]
Ok ça a marché pour moi aussi

**Comment by isbkch** [comment]
Mais Des que je ferme la page, tout redevient comme avant. Même l'histogramme arrête d'enregistrer les données

**Comment by francispoisson** [comment]
Quand tu parles de la dernière mise à jour, tu parles de la dernière mise à jour de Home assistant 2021.2.1?

**Comment by isbkch** [comment]
Oui- j'ai inclus un lien vers la mise à jour en question dans mon commentaire

**Comment by francispoisson** [comment]
Tu peux essayer la dernière version, je crois que c'est ok.

**Comment by francispoisson** [comment]
Dernière version à tester.

**Comment by isbkch** [comment]
Installé et redémarré. Ça fonctionne comme il faut pour le moment!
