### ISSUE TITLE
Gradateurs recconus seulement commes capteurs (sensor) 

### ISSUE THREAD

**Issue by kayrozen** [francispoisson/hilo#15]
J'ai un gradateur et il est seulement recconu comme sensor et non pas une switch. Cool d'avoir la consommation mais le piloter serait génial. C'est une limitation de l'API?

(beau travail btw!)

**Comment by francispoisson** [comment]
Non, ce n'est pas une limitation de l'API, je n'ai tout simplement pas de gradateur, je n'ai donc pas développé cette fonctionnalité.

**Comment by kayrozen** [comment]
@francispoisson Comment puis-je t'aider à l'ajouter en sachant que je ne suis pas dev ? Je suis parcontre bien installé pour faire de la capture de paquets via android.

**Comment by francispoisson** [comment]
Tu peux essayer la branche "dev":
https://github.com/francispoisson/hilo/tree/dev

**Comment by kayrozen** [comment]
Semble y avoir une erreur de définition 

`
Logger: homeassistant.components.light
Source: custom_components/hilo/light.py:16
Integration: Light (documentation, issues)
First occurred: 9:09:11 AM (1 occurrences)
Last logged: 9:09:11 AM
Error while setting up hilo platform for light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hilo/light.py", line 16, in setup_platform
    add_entities([HiloSwitch(hass.data[DOMAIN], i)])
NameError: name 'HiloSwitch' is not defined

`

**Comment by kayrozen** [comment]
Yes ! Elle est maintenant détectée. J'ai le boolean pour on-off mais pas l'intensité. 

Dans les états d'entitées : 

> supported_color_modes:
>   - onoff
> color_mode: onoff
> friendly_name: Lumière cuisine
> supported_features: 0
>

**Comment by francispoisson** [comment]
Et maintenant?

Le mer. 9 juin 2021, à 09 h 28, Kay Rozen ***@***.***> a
écrit :

**Comment by kayrozen** [comment]
On y est presque !! Le slider est inversé. 0 = full bright , 100 = off. 

Merci beaucoup de ton temps ! t'es un coffeetip ou same ?

**Comment by francispoisson** [comment]
Tu peux réessayer. Hilo fonctionne avec du 0-100 et HA du 0-255.

Le mer. 9 juin 2021, à 09 h 49, Kay Rozen ***@***.***> a
écrit :

**Comment by kayrozen** [comment]
Malheureusement :/

> Logger: homeassistant.components.websocket_api.http.connection
> Source: custom_components/hilo/light.py:59
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 10:54:03 AM (2 occurrences)
> Last logged: 10:54:20 AM
> [140054621681216] 'brightness'
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
>     await handler.job.target(service_call)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
>     await self.hass.helpers.service.entity_service_call(
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
>     future.result()  # pop exception if have
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
>     await result
>   File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 376, in async_handle_light_on_service
>     await light.async_turn_on(**params)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in async_turn_on
>     await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/hilo/light.py", line 59, in turn_on
>     self._h.set_attribute('Intensity', kwargs[ATTR_BRIGHTNESS]/255*100, self.index)
> KeyError: 'brightness'

**Comment by francispoisson** [comment]
Ok. encore une nouvelle version à tester :)

Le mer. 9 juin 2021, à 10 h 55, Kay Rozen ***@***.***> a
écrit :

**Comment by kayrozen** [comment]
> ogger: homeassistant.components.websocket_api.http.connection
> Source: custom_components/hilo/light.py:59
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 11:13:02 AM (2 occurrences)
> Last logged: 11:13:09 AM
> [139947368072432] name 'attr_brightness' is not defined
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
>     await handler.job.target(service_call)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
>     await self.hass.helpers.service.entity_service_call(
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
>     future.result()  # pop exception if have
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
>     await result
>   File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 376, in async_handle_light_on_service
>     await light.async_turn_on(**params)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in async_turn_on
>     await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/hilo/light.py", line 59, in turn_on
>     self._h.set_attribute('Intensity', kwargs.get(attr_brightness, 255)/255*100, self.index)
> NameError: name 'attr_brightness' is not defined
>

**Comment by francispoisson** [comment]
Oups, petite erreur de majuscule. Encore une autre...

Le mer. 9 juin 2021, à 11 h 14, Kay Rozen ***@***.***> a
écrit :

**Comment by jeromelefeuvre** [comment]
Salut, j'ai aussi des gradateurs et c'est tout bon pour moi. Mes 2 gradateurs marchent, good job!
