### ISSUE TITLE
Folder in place. Now where do we put user/pass ?

### ISSUE THREAD

**Issue by macgaver** [francispoisson/hilo#18]
Trying to follow the brief documentation, I have put the files in config/custom_components/hilo
I restarted homeassistant and I can see in the startup log that it is being discover (warning about plugin not tested)
Now where is that configuration file where I put my user and password ?

**Comment by masteryodha** [comment]
If you have "File Editor" installed as a HACS plugin you can edit the file directly from home assistant.

Or you can navigate to the folder "config" where home assistant is installed.

You'll find the configuration.yaml in this folder

**Comment by macgaver** [comment]
Awesome, it's working. Thanks for the quick reply.
I'm novice with Home Assistant
