### ISSUE TITLE
Missing switch when configured as dimmer

### ISSUE THREAD

**Issue by macgaver** [francispoisson/hilo#19]
More enhancement request than bug probably
Everything is working perfectly, I can see thermostat and the switch configured as “on/off” mode. This is a parameter on the switch itself (not the Hilo app).

Thanks for the software, really like it !

**Comment by francispoisson** [comment]
I am not sure I understand, can you provide screenshots? Thanks.

**Comment by macgaver** [comment]
Sorry to be not precise enough. Here some screenshot, you can see that a few switches are configured as dimmer (not switches). They are the same hardware, just a setting you can set on the switch itself when you want to enable dimming the connected light. Second screenshot are the only 2 switches I see in homeassistant. I can see everything, except the the switches configured as dimmer
![image](https://user-images.githubusercontent.com/12750011/129203503-c121efc5-fb7c-42bd-9172-3efc50699b87.png)

![image](https://user-images.githubusercontent.com/12750011/129203952-4d1d8950-faaa-405f-a9c8-7fa0d69bbdc4.png)

**Comment by francispoisson** [comment]
They should be there. They are not considered switch in HA, but light fixture. They should have en entity ID that start with "light."

**Comment by macgaver** [comment]
I see them as sensor dimmer:
![image](https://user-images.githubusercontent.com/12750011/129240719-ad6c90ef-0842-4927-aee2-ae0889d15175.png)

But nothing about light:
![image](https://user-images.githubusercontent.com/12750011/129240749-fa2afe9b-be7d-49b8-8c36-ed69fbbd2799.png)

Am I supposed to be able to control these dimmer in HA like we do for switches ? Or it's expected that we only see power usage for dimmer ?

**Comment by francispoisson** [comment]
Try upgrading to the last version. There should be a light.py file in the hilo integration directory.

**Comment by macgaver** [comment]
Thanks for the fix. It is now working, I see the dimmers under light, and I can control them perfectly !
