### ISSUE TITLE
les données de consommation du compteur ne sont pas disponible pour les statistiques de HomeAssistant

### ISSUE THREAD

**Issue by skimaniac** [francispoisson/hilo#20]
Lorsque on essaie de configurer les statistiques de consommation électrique dans HA (configurer--> énergie) dans Grid consumption on n'a pas l'option d'ajouter SmartEnergyMeter (compteur Hydro).

https://www.home-assistant.io/more-info/statistics/

**Comment by francispoisson** [comment]
Je te réfère à l'article de HA sur la gestion de l'énergie:
https://www.home-assistant.io/docs/energy/faq/

Hilo ne fournit que des capteurs de puissance et non d'énergie. La meilleure chose à faire est d'utiliser l'intégration "intégration" qui permet de convertir la puissance en énergie.

J'ai ajouté ceci dans le fichier configuration.yaml:
sensor:
  - platform: integration
    source: sensor.smartenergymeter
    name: energy_spent
    unit_prefix: k
    method: left
    round: 2

**Comment by skimaniac** [comment]
Merci pour les éclaircissement sur Energie vs puissance ;) et l'intégration semble fonctionner, j'ai des données en surveillant avec l'outil de développement, mais pas encore dans le tableau d'énergie, mais ça devrait venir.

est-ce qu'il y a le même type de passe-passe à faire pour suivre la consommation des prises et interrupteur hilo?

merci de ton aide.
