### ISSUE TITLE
hilo.hiloapi - Request for access token failed

### ISSUE THREAD

**Issue by macgaver** [francispoisson/hilo#23]
Since now more than 24h, it look like my system is failing to get the new token from Hilo. No change on my homeassistant. 

What I see in the logs:
2021-08-18 13:07:41 WARNING (SyncWorker_2) [custom_components.hilo.hiloapi] Request for access token failed.

It's the same after restarting. Is it just me ? The app still work fine, and no password changes

**Comment by francispoisson** [comment]
You can reset your Hilo password, that should work.

Le mer. 18 août 2021, à 13 h 20, macgaver ***@***.***> a
écrit :

**Comment by macgaver** [comment]
Indeed, problem fixed.  Not sure why my password needed a reset but that did the trick !
Thanks for the quick answer

**Comment by francispoisson** [comment]
The day Hilo will provide an official API, it will be easier to monitor
what's going on...

Le mer. 18 août 2021, à 14 h 58, macgaver ***@***.***> a
écrit :
