### ISSUE TITLE
Integrate with new Energy Dashboard

### ISSUE THREAD

**Issue by isbkch** [francispoisson/hilo#24]
Y'a tu une façon de recuperer la consommation en temps reel qu'on voit sur le dashboard Hilo et la rendre réutilisable pour le nouveau Energy Dashboard?

**Comment by francispoisson** [comment]
Je te réfère à l'article de HA sur la gestion de l'énergie:
https://www.home-assistant.io/docs/energy/faq/

Hilo ne fournit que des capteurs de puissance et non d'énergie. La meilleure chose à faire est d'utiliser l'intégration "intégration" qui permet de convertir la puissance en énergie.

J'ai ajouté ceci dans le fichier configuration.yaml:
sensor:

platform: integration
source: sensor.smartenergymeter
name: energy_spent
unit_prefix: k
method: left
round: 2

**Comment by isbkch** [comment]
J'ai suit ton example et j'ai fait pareil. Merci

![404B315C-907D-4C3E-A6C8-3204F4358EAE](https://user-images.githubusercontent.com/216867/130376123-9b876fb3-cf77-444e-a093-a6974d0e08ad.jpeg)

**Comment by masteryodha** [comment]
Le ticket est fermé, mais je voulais juste ajouter un peu d'information supplémentaire.

Les entités de thermostat et d'interrupteur ont tous aussi des capteurs pour la consommation en Watt.
Vous pouvez donc ajouter un sensor avec la plateforme "integration" pour chaque thermostat et interrupteur et ensuite les ajouter comme appareil individuel dans le Dashboard "Énergie".

Pour que les entités apparaissent, j'imagine qu'il faut laisser du temps pour que le sensor possède une valeur ou faites comme moi et ajouter les propriétés suivantes aux différents sensor

`device_class: energy`
`unit_of_measurement: kWh`

**Comment by isbkch** [comment]
J'ai essayé de les rajouter mais j'ai cette erreur:

```
invalid config for [sensor.integration]: [unit_of_measurement] is an invalid option for [sensor.integration]. Check: sensor.integration->unit_of_measurement. (See ?, line ?)
```

Je les ajoute comme ça:
```
- platform: integration
  source: sensor.thermostat_cuisine
  name: thermostat_cuisine
  device_class: energy
  unit_of_measurement: kWh
```

Vois tu une erreur dans mes configs?

**Comment by masteryodha** [comment]
Désolé, j'ai pas été assez clair dans mon commentaire plus haut, mes excuses.

Donc, la première étape est d'ajouter des sensors avec la plateforme integration, comme mentionné plus haut par francispoisson: 

`
  - platform: integration
    source: sensor.chauffage_salon
    name: energy_chauffage_salon
    unit_prefix: k
    method: left
    round: 2
`

Il faut certainement un reboot par la suite pour que la nouvelle entité "energy_chauffage_salon" apparaissent maintenant dans la liste de tes entités.

Je crois qu'étant donné que nous sommes en été et que le chauffage ne fonctionne pas, l'entité se créé, mais il lui manque des attributs.  Ce qui fait que l'entité n'est pas disponible dans le dashboard d'Énergie.

Donc, tu pourrais monter le chauffage et attendre quelques temps que la valeur de l'entité change et soit tout parfaite (je n'ai pas testé).

Ou tu fais comme moi (mon commentaire plus haut qui n'était pas clair) : 
Dans Outils de développement, tu recherches la nouvelle entité : energy_chauffage_salon, tu ajoutes les 2 attributs mentionnés et tu cliques sur "Définir l'état".
Par la suite, les entités sont dispo dans le dashboard Energy.
![image](https://user-images.githubusercontent.com/43122656/132109621-b48e9470-567e-459b-83c0-744147d316fd.png)

**Comment by isbkch** [comment]
C'est parfait! Merci pour la clarification! J'ai les devices affichés maintenant sur le energy dash.
