### ISSUE TITLE
Contrôle des lumières très irrégulier

### ISSUE THREAD

**Issue by Eradash** [francispoisson/hilo#25]
Contrôler les lumières avec un pourcentage est pratiquement impossible
Utiliser le contrôle On/Off est plus facile, mais pas parfait
L'application indique 10000% quand on active la lumière dans HA, et revient à 100% après un court moment
L'application indique 10000% quand on met la lumière à 100% dans HA, et revient à 16% après un court moment
L'indication de l'état de la lumière n'est pas bonne dans HA

**Comment by francispoisson** [comment]
Je n'ai pas d'interrupteurs à la maison pour pouvoir tester. Si vous désirez revoir le code ça serait aidant.

**Comment by Eradash** [comment]
La synchronisation entre les actions effectuées sur l'application et HA est très lente
La synchronisation entre les actions physique sur le gradateur et HA ne fonctionne pas encore, je vais y retravailler un autre fois. 
Normalement ça ne cause pas de problèmes, excepté si on veut réagir aux changements d'états pour des automations

**Comment by thib5** [comment]
Merci encore pour cette intégration, je l’utilise depuis 2 jours et tout semble beau en effet mais j’ai le meme porbleme avec les switch

Le contrôle des switch va bien mais si j’utilise manuellement les switch la synchronisation ne ce fait pas ( ou très lente )

**Comment by francispoisson** [comment]
Le problème, c'est que la communication avec Hilo se fait sur le cloud
plutôt que localement.

Si j'étais vous, je connecterais les appareils autre que les thermostats
directement à HA avec une dongle ZigBee zzh et l'intégration ZHA.

**Comment by thib5** [comment]
C’est pas grave, je souslignais le problème simplement !
