### ISSUE TITLE
Ampoules non détectées

### ISSUE THREAD

**Issue by vgibara** [francispoisson/hilo#27]
Salut !

Superbe boulot avec hilo ! Bravo !

Une question toutefois. J'ai des thermostats et des prises intelligentes, que je peux voir dans HA. Mais j'ai aussi des ampoules que je ne vois pas. Est-ce normal ? Je vois pourtant le fichier light.py mais je crois que ce n'est que pour les dimmer. Je me trompe ?

Comment puis-je ajouter le support pour les ampoules ?

Merci !!

**Comment by francispoisson** [comment]
Une autre personne a proposé une modification dans les "pull request", tu
peux tester ça et confirmer que ça fonctionne, je n'ai pas de lumières ici.

**Comment by vgibara** [comment]
Effectivement. Le pull gère les Dimmer (interrupteurs), mais pas les ampoules. J'ai modifié temporairement la ligne 15 pour:

if(hass.data[DOMAIN].d[i].deviceType == 'LightDimmer' or hass.data[DOMAIN].d[i].deviceType == 'WhiteBulb' or hass.data[DOMAIN].d[i].deviceType == 'ColorBulb'):


Ça fonctionne très bien. Toutefois, je cherche encore comment gérer les couleurs... je pourrais faire un vrai pull request et faire les changements pour un éventuel commit. Quelqu'un peut m'aider avec la gestion des couleurs ?

**Comment by francispoisson** [comment]
Pour le colorbulb, où en es-tu?

Peux-tu tester ce code dans ton environnement de programmation pour voir quelles sont les attributs des ampoules de couleur?

`from hiloapi import *

def main():
    h = Hilo('username', 'password')

    h.update()

    print(h.d[0].name)
    print(h.d[0].supportedAttributes)
    print(h.d[0].settableAttributes)


if __name__ == "__main__":
    main()`

**Comment by vgibara** [comment]
J'ai peu avancé. J'en étais rendu à setter des valeurs pour ces variables
justement. ColorMode, Hue, Saturation et Intensity. Mais j'ai pas fini l ;)

Lumière Cuisine 1
OnOff, Intensity, Disconnected, Hue, Saturation, ColorTemperature
OnOff, Intensity, ColorMode, Hue, Saturation, ColorTemperature

Le mar. 5 oct. 2021, à 08 h 54, francispoisson ***@***.***> a
écrit :

**Comment by francispoisson** [comment]
Pour les ampoules, ça semble ok pour la détection. Je vais créer une nouvelle issue pour l'attribut "couleur".
