### ISSUE TITLE
Mise à jours inexistante ou super lente de tout les appareils 

### ISSUE THREAD

**Issue by thib5** [francispoisson/hilo#30]
Bonjour, je sais que vous faites votre possible et que l'api de Hilo ne vous permet pas grand chose mais j'ai peut-être un problème different que juste un problème de mauvais api ... 

En fait mes thermostat ne mettre pas a jours la temperature des piece ... je ne reçois pas non plus de mise ;a jours des switch si le status change manuellement... bref les commande marche super bien mais le status aucunement. 

Pourtant si je redémarre home assistant tout ce met a jour... on pourrait donc peut-être forcer une mise à jours tout les 5 minutes ? ça serait amplement suffisant pour moi honnêtement 

J'ai déjà tenter de réinstaller le component mais ça na rien changer

**Comment by francispoisson** [comment]
As-tu installé la dernière version?

Hilo a fait des modifications cette semaine rendant cet aspect
non-fonctionnel. J'ai fait un correctif hier.

**Comment by thib5** [comment]
Oui... comme je dit j'ai tout réinstaller donc par la bande et réinstallant j'ai installer la nouvelle version

**Comment by francispoisson** [comment]
Tu peux décommenter la ligne 34 du fichier __init.py. Ça devrait être ok.

**Comment by thib5** [comment]
Ca semble avoir régler le problème pour les sensor de température mais pas pour les switch… honnêtement c’est suffisant pour moi merci ! Sinon croyez vous que ca valle la peine que j’essai de suprimer complètement le dossier dans custom_component … quand je dit que j’ai réinstallé en fait je l’ai fait a partir de hacs… je l’ai supprimé dans hacs pour ensuite le réinstaller

**Comment by francispoisson** [comment]
Je ne sais pas, je ne connais pas beaucoup HACS. 

Pour les lumières, peux-tu retester avec la dernière version?

**Comment by thib5** [comment]
J'ai tout supprimer et réinstaller manuellement et .. Non toujours pas d'update pour les lumières... Mais comme je disait c'est surtout les update des sensor de temperature que je voulais et ça semble régler merci !
