### ISSUE TITLE
Connexion impossible avec mot de passe avec caractères spéciaux

### ISSUE THREAD

**Issue by isbkch** [francispoisson/hilo#4]
My thermostats are no showing + I'm getting this error in the logs:

Traceback

```
Logger: homeassistant.helpers.entity
Source: custom_components/hilo/hiloapi.py:152
First occurred: 10:13:03 AM (4 occurrences)
Last logged: 10:16:03 AM

Update for binary_sensor.defi_hilo fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hilo/binary_sensor.py", line 50, in update
    self._h.update()
  File "/config/custom_components/hilo/hiloapi.py", line 239, in update
    self.refreshToken()
  File "/config/custom_components/hilo/hiloapi.py", line 152, in refreshToken
    if time.time() > self.access_token_expiration:
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```

**Comment by francispoisson** [comment]
Peux-tu essayer les modifications ici et me dire ce que le journal affiche?

**Comment by isbkch** [comment]
J'ai mis a jour le fichier, removed the cache and restarted HA. 
En plus de l'erreur habituelle ci-deussous

```
Logger: homeassistant.helpers.entity
Source: custom_components/hilo/hiloapi.py:154
First occurred: 11:38:03 AM (1 occurrences)
Last logged: 11:38:03 AM

Update for binary_sensor.defi_hilo fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hilo/binary_sensor.py", line 50, in update
    self._h.update()
  File "/config/custom_components/hilo/hiloapi.py", line 241, in update
    self.refreshToken()
  File "/config/custom_components/hilo/hiloapi.py", line 154, in refreshToken
    if time.time() > self.access_token_expiration:
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```

J'ai une nouvelle:
```
Logger: custom_components.hilo.hiloapi
Source: custom_components/hilo/hiloapi.py:110
Integration: Hilo HA integration (documentation, issues)
First occurred: 11:39:08 AM (1 occurrences)
Last logged: 11:39:08 AM

Request for access token failed.
```

J'utilise mon email comme username, je sais pas si j'ai un username proprement dit

**Comment by francispoisson** [comment]
C'est ce que je pensais, ça semble être un problème avec ton username et ton password. Essaie de resetter ton mot de passe dans l'application Hilo.

**Comment by isbkch** [comment]
Je vais verifier ça. Mon mot de passe actuel contient des caracteres speciaux, est ce que ça poserait probleme ?

**Comment by francispoisson** [comment]
Réessaie avec le même mot de passe, ça m'avait déjà fait ça...

Sinon, essaie un mot de passe un peu plus simple.

**Comment by isbkch** [comment]
Je viens d'essayer avec un passe plus simple, maintenant j'ai cette erreur:

```
Logger: homeassistant.setup
Source: custom_components/hilo/hiloapi.py:130
First occurred: 11:49:11 AM (1 occurrences)
Last logged: 11:49:11 AM

Error during setup of component hilo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hilo/__init__.py", line 29, in setup
    hass.data[DOMAIN] = Hilo(username, password)
  File "/config/custom_components/hilo/hiloapi.py", line 130, in __init__
    exec("%s = %s" % (s, s2))
  File "<string>", line 1, in <module>
KeyError: 'power'
```

**Comment by isbkch** [comment]
Je viens d'essayer plusieurs combinaisons:

Quand je met un password simple, j'ai cette erreur
```
Logger: homeassistant.setup
Source: custom_components/hilo/hiloapi.py:130
First occurred: 11:49:11 AM (1 occurrences)
Last logged: 11:49:11 AM

Error during setup of component hilo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hilo/__init__.py", line 29, in setup
    hass.data[DOMAIN] = Hilo(username, password)
  File "/config/custom_components/hilo/hiloapi.py", line 130, in __init__
    exec("%s = %s" % (s, s2))
  File "<string>", line 1, in <module>
KeyError: 'power'
```

Quand je met un password robuste (avec des caracteres speciaux) j'ai les deux erreurs 
`Request for access token failed.` et `TypeError: '>' not supported between instances of 'float' and 'NoneType'`

**Comment by francispoisson** [comment]
C'est deux problèmes distincts.

Tu peux ouvrir un autre billet pour le problème avec le mot de passe simple.

**Comment by francispoisson** [comment]
Quels genres de caractères spéciaux utilises-tu?

**Comment by isbkch** [comment]
generé depuis Bitwarden: https://bitwarden.com/password-generator/ avec une longueur de 16

<img width="1170" alt="Screen Shot 2021-02-02 at 12 37 33 PM" src="https://user-images.githubusercontent.com/216867/106639934-7ab05700-6553-11eb-9383-1d7356f7b7cf.png">

**Comment by isbkch** [comment]
Super. Oui, j'en ai crée

**Comment by francispoisson** [comment]
Peux-tu réessayer avec cette version de hiloapi.py et un mot de passe avec caractères spéciaux? Merci.

**Comment by isbkch** [comment]
Done. J'ai une seule erreur maintenant. `Request for access token failed.`

**Comment by francispoisson** [comment]
Et avec un mot de passe simple?🤔

**Comment by isbkch** [comment]
Ça donne ça : `Logger: custom_components.hilo.hiloapi
Source: custom_components/hilo/hiloapi.py:134 
Integration: Hilo HA integration (documentation, issues) 
First occurred: 8:22:18 PM (1 occurrences) 
Last logged: 8:22:18 PM

KeyError`

**Comment by francispoisson** [comment]
Est-ce que tes appareils sont ajoutés?

Le mar. 2 févr. 2021 20 h 46, iLyas Bakouch <notifications@github.com> a
écrit :

**Comment by isbkch** [comment]
Oui! Je viens de revérifier. Je trouve maintenant les appareils sous climate.xxx

**Comment by francispoisson** [comment]
Super, est-ce que ta switch y est aussi et est-ce qu'elle fonctionne?

Je comprends bien les deux problèmes et je devrais être capable de régler ça dans les prochains jours.

**Comment by isbkch** [comment]
Oui la switch fonctionne bien aussi.
Merci pour le support impeccable. J'attends la version finale!

**Comment by francispoisson** [comment]
Autre question. Dans tes capteurs de puissance (sensor.xxx), est-ce que la puissance de ta switch fonctionne? Est-ce qui y a la consommation est affichée dans l'application Hilo?

**Comment by isbkch** [comment]
Oui. L'application Hilo affiche 4W par contre, j'imagine que c'est arrondi 

<img width="406" alt="Screen Shot 2021-02-03 at 9 34 25 AM" src="https://user-images.githubusercontent.com/216867/106761717-1e0c7500-6603-11eb-9705-7664c2dbf3be.png">

**Comment by francispoisson** [comment]
Ok, je pense que tes problèmes sont réglées pour le moment.

**Comment by isbkch** [comment]
Je pense aussi. Le seul bémol c'est que j'utilise un mot de passe vraiment simple depuis hier

**Comment by francispoisson** [comment]
Tu peux mettre à jour ta version et remettre un mot de passe complexe, ça devrait fonctionner. J'ai mergé la nouvelle version dans le master.

**Comment by isbkch** [comment]
Je confirme que ça fonctionne bien avec le password complexe
