### ISSUE TITLE
Ajout d'un sensor pour la consommation du domicile

### ISSUE THREAD

**Issue by darkjeff99** [francispoisson/hilo#41]
Je pense qu'il pourrait être interessant d'avoir un sensor avec la consommation de la maison.

Je ne connais pas du tout le framework autour de HA, mais j'ai déjà récupérer  le call API. 

```
'https://apim.hiloenergie.com/Automation/v1/api/Locations/' + str(self.__location_id) + '/History/Energy2?timescale=Week&date=2021-10-31'
```

Si on me guide un peu je pourrais l'ajouter.

**Comment by valleedelisle** [comment]
Je sais que ce n'est pas exactement ce que tu voulais, le but ici est de faire un leverage des calculs du dashboard de home assistant.
