### ISSUE TITLE
Unable to get access token

### ISSUE THREAD

**Issue by JPLavigne** [francispoisson/hilo#46]
Hi,

I'm trying to set up this custom integration for the first time. 

I get errors while starting HA. I get a 400 error code while posting to this URL : 
![image](https://user-images.githubusercontent.com/42275364/142479059-fbde0fe3-d491-4213-a082-5a889d7ccdc1.png)

I'm pretty sure I've downloaded and configured the integration correctly.

Has this URL changed or is this on my end?

Thanks,

**Comment by JPLavigne** [comment]
If I test this call, if get missing required parameter : grant_type
![image](https://user-images.githubusercontent.com/42275364/142480858-fdfb896e-c46f-4c2d-ada5-044f9b6a1dcf.png)

The parameter is included in the body of the request.
![image](https://user-images.githubusercontent.com/42275364/142481116-ba3023bf-fbff-4e43-906d-2d9003f7607f.png)

**Comment by francispoisson** [comment]
Tu peux essayer la dernière version.

**Comment by JPLavigne** [comment]
Merci, ça fonctionne!
