### ISSUE TITLE
Plugin installer

### ISSUE THREAD

**Issue by jfmeuniercow** [francispoisson/hilo#59]
Bonjour. J'ai installer le plugin dans mon PI. Je le vois dans l'intégrations dans HACS. Comment faire pour le faire démarrer afin de le voir dans Homekit ?

**Comment by FrancoLoco** [comment]
Es-tu un nouveau client des derniers jours? Si oui il est possible que ca ne marche pas actuellement, car selon mes observations, Hilo retourne les états de mes appareils figés dans le temps tel que c'était il y a quelques jours... On espère que l'intégration pourra être corrigée pour supporter le nouveau fonctionnement d'Hilo 🤞 .

**Comment by jfmeuniercow** [comment]
Allo Franco,

Oui je le suis, mais aussi nouveau sur Homeassistant. Je ne suis pas certain d'avoir fait la bonne chose. Je sais bien installer des apps dans Homeassistant, mais pour Hilo, j'ai pas moyen de rien démarrer. 

Au mois, tu les vois, mais il sont figer. Cela te dérangerais de m'aider en me rejoignant par courriel au j.francois.meunier@me.com? Merci.

**Comment by aomann** [comment]
As-tu modifié le fichier de configuration "configuration.yaml" afin d'y inclure tes informations de connexion à Hilo?

**Comment by jfmeuniercow** [comment]
Allo Aomann,

Oui. Le fichier n'y était pas, alors je l'ai créé et mis dans le dossier Hilo.

**Comment by jfmeuniercow** [comment]
Ho Yeah !!!! Ça marche.... Cool.....

**Comment by jfmeuniercow** [comment]
Merci pour votre aide. Super rapide.
