### ISSUE TITLE
KeyError: 'power'

### ISSUE THREAD

**Issue by isbkch** [francispoisson/hilo#6]
Quand j'utilise un password simple, j'ai cette erreur

```
Logger: homeassistant.setup
Source: custom_components/hilo/hiloapi.py:130
First occurred: 11:49:11 AM (1 occurrences)
Last logged: 11:49:11 AM

Error during setup of component hilo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hilo/__init__.py", line 29, in setup
    hass.data[DOMAIN] = Hilo(username, password)
  File "/config/custom_components/hilo/hiloapi.py", line 130, in __init__
    exec("%s = %s" % (s, s2))
  File "<string>", line 1, in <module>
KeyError: 'power'
```

**Comment by francispoisson** [comment]
En fait ici, ta connexion fonctionne, c'est un problème tout autre qu'il faudra approfondir. 

Quels appareils as-tu dans ton système Hilo? Juste des thermostats?

**Comment by isbkch** [comment]
Les thermostats plus un EZ smart switch

**Comment by francispoisson** [comment]
Ok, c'est peut-être le EZ smart switch qui fait boguer, je n'ai pas testé avec ça puisque j'en ai pas. Je vais surement te demander de tester quelque chose.

**Comment by isbkch** [comment]
Je vois. je fais malheureusement pas de Python, j'aurai aidé sinon... Mais il me semble qu'ajouter une condition pour accepter seulement les appareils testés au préalable - s'il y'a moyen de les identifier par le type - serait un bon fix ?

**Comment by francispoisson** [comment]
Le problème c'est qu'à cette étape, c'est en train de récupérer l'information. Tu peux essayer ça en même temps.
