### ISSUE TITLE
Unavailable entities

### ISSUE THREAD

**Issue by loubersac** [francispoisson/hilo#60]
I've had my Hilo installation a few days ago and I've been playing with your integration since but cannot find any solution for that problem.

> All `climate `entities are created but unavailable.
> All `sensor `for `light `and `thermostat `entities are created but unavailable.
> All `light `entities are created but only 2 are available and working once intagrated into a dashboard (why those two in particular I have no idea).
> All `sensor.hilo_energy_`  are created and available.

I've tried reinstalling the integration, moving my Hilo Base on the same VLAN as my Hassio VM but nothing change. I still only have two working light switches and cannot control anything else. Any ideas what might cause this and how to fix it?

Thanks!

**Comment by francispoisson** [comment]
Merci de vous référer à ce repo pour les développements futurs:

https://github.com/dvd-dev/hilo/

**Comment by loubersac** [comment]
Merci, ca fonctionne a merveille!
