### ISSUE TITLE
Unable to find state for sensor.hilo_energy_total_daily_low

### ISSUE THREAD

**Issue by isbkch** [francispoisson/hilo#62]
J'ai cette erreur dans mes logs depuis plusieurs jours

```
This error originated from a custom integration.

Logger: custom_components.hilo.api
Source: custom_components/hilo/api.py:326
Integration: Hilo HA integration (documentation, issues)
First occurred: 11:04:19 AM (37 occurrences)
Last logged: 11:08:49 AM

check_tarif: Unable to find state for sensor.hilo_energy_total_daily_low
```

**Comment by francispoisson** [comment]
De plus, tes appareils ne se mettent probablement plus à jour. Cet intégration est désuète puisque Hilo a fait de grosses modifications.

**Comment by isbkch** [comment]
Oui, rien ne fonctionne plus en fait, mais c'est pas grave, j'apprecie l'effort que vous mettez dessus, j'attendrai le temps qu'il faut
